Existing enrollment actions
Hobstweedl/ddc pull request #48
Opened 2018-02-23 21:08 UTC by winterj

Made enrollments polymorphic with classdays and dates, rather then storing the ID on the enrollment. For editing, it made the most sense to keep it per-enrollment, rather then treating the "group" of enrollments the same, since a student could take Monday for a few months and then start taking Thursday as well.

2018-02-23 21:57 UTC, Hobstweedl requested changes

2018-02-23 21:57 UTC, Hobstweedl commented on app/Enrollment.php
> +      $otherEnrollments = DB::table('class_days')
I don't like this. Try to either do something with Eloquent, or wrap all of this logic up into 1 function in the model and call it.

2018-02-23 21:57 UTC, Hobstweedl commented on app/Http/Controllers/EnrollmentsController.php
> +    $daysEnrolledInClass = DB::table('class_days')
Same here

2018-02-24 02:08 UTC, winterj commented
Removed "other" enrollments stuff.

2018-02-25 02:26 UTC, winterj commented on app/Http/Controllers/EnrollmentsController.php
> +    $daysEnrolledInClass = DB::table('class_days')
Done and done.

2018-03-01 15:45 UTC, Hobstweedl approved these changes

2018-03-01 15:57 UTC, merged